### ISSUE TITLE
Reuse section of README is incorrect

### ISSUE THREAD

**Issue by northbear** [libopencm3/libopencm3-examples#123] opened 2016-02-29 08:21 UTC
Description of steps how to reuse libopencm3-examples build system in his own project is not proper. There also should be contained a step of copying ld_script (it's required for stm32f4_discovery at least). 
It would be good idea to add basic templates of makefiles for new projects for each platforms.

**Comment by karlp** [comment] 2016-10-01 16:17
closing as a duplicate of #76

**Closed by karlp** 2016-10-01 16:17 UTC
